### ISSUE TITLE
Using sctp module in a docker container

### ISSUE THREAD

**Issue by razaborg** [sctplab/SCTP_NKE_ElCapitan#2]
I installed the org.sctp.nke.SCTP kernel module in my mac OS Sierra macbook successfully, but I would like to use it inside a docker container.

I tried to start my container using the *--cap-add SYS_MODULE* argument, and installing the *libsctp-dev lksctp-tools kmod* packages in the container, but when I run a *modprobe SCTP*, here is the error I get:

`modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.9.13-moby/modules.dep.bin'
modprobe: FATAL: Module SCTP not found in directory /lib/modules/4.9.13-moby`

Any clues ? 
I'll try to ask also to ask on the docker side, maybe they are more likely to help me...

**Comment by tuexen** [comment]
> I installed the org.sctp.nke.SCTP kernel module in my mac OS Sierra macbook successfully,
> but I would like to use it inside a docker container.

The org.sctp.nke.SCTP kernel module is for the Mac OS X kernel. Not for Linux.

All the rest of your mail refers to Linux and not to Mac OS X. Even if you run a VM on Mac OS X.
I'm not an expert on Linux or Docker, but I think you can't use the Linux kernel stack in a docker container.

**Comment by razaborg** [comment]
Yes you're right.
My investigations on docker for mac taught me that docker containers runs in fact over a hyperkit VM, so it has a priori nothing to do with your mac OS module (which works pretty good beyond that).
I'll close the issue, thanks.
