### ISSUE TITLE
i have install it as the README.md  do ,but i still can't use it  by jdk-8. can anyone tell me why?

### ISSUE THREAD

**Issue by apri30th** [sctplab/SCTP_NKE_ElCapitan#3]
i can't compile  a simple java example with jdk-8 . 
 my jdk is 
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

when i compile the java sctp program ， the error is as below 
SCTP not supported on this platform .

**Comment by tuexen** [comment]
I guess you would need to build the jdk with SCTP support, which most likely wasn't done, since the SCTP support is not provided by Apple.
I'm not sure, but might have more luck with using FreeBSD, Linux or Solaris.

**Comment by tuexen** [comment]
I have tested FreeBSD. The openjdk from the ports collection supports SCTP.
