### ISSUE TITLE
support for 10.13?

### ISSUE THREAD

**Issue by cartazio** [sctplab/SCTP_NKE_ElCapitan#4]
can either of your kernel extensions be safely used / adapted to high sierra? 
thanks

**Comment by tuexen** [comment]
I haven't tested it yet... Wasn't sure if there is still interest in it. But I can test it and provide some instructions for using, if it works.

**Comment by cartazio** [comment]
I’m juggling a few other related rabbit holes and would at least be
curious.  :)

**Comment by noteax** [comment]
I've interested in 10.13 support (as well as few other devs in our team). @tuexen, I could help llittle bit if you provide some test steps to perform.

**Comment by andreasfink** [comment]
The version I tested does load under 10.13 but doesn't do anything.
I will see if I can get it to work.

**Comment by tuexen** [comment]
I have added a repository for the NKE running on High Sierra: [SCTP_NKE_HighSierra](https://github.com/sctplab/SCTP_NKE_HighSierra). I have not build an install image. Will do so tomorrow.

**Comment by tuexen** [comment]
Fix one last build issue for High Sierra and put an install image online. If there are any issues with the NKE on High Sierra, please file an issue under [SCTP_NKE_HighSierra](https://github.com/sctplab/SCTP_NKE_HighSierra).
